/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Model.BookingSlipModel;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.*;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Toolkit;
import java.io.FileOutputStream;

import javax.swing.JPanel;
/**
 *
 * @author hello
 */
public class BookingSlipView extends javax.swing.JFrame {
    private BookingSlipModel bsv1;
    /**
     * Creates new form BookingSlipView
     */
    public BookingSlipView() {
        initComponents();
        setTitle("Booking Slip");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/logo.png")));

    }
    
    public void setBookingSlipViewModel(BookingSlipModel bsv1){
        this.bsv1=bsv1;
        updateLabels();
    }
   
    private void updateLabels(){
        String vehicleNo=bsv1.getVechicleNumber();
        String brand=bsv1.getBrand();
        String model=bsv1.getModel();
        String specialReq=bsv1.getSpecial_request();
        String borrowDate=bsv1.getBorrow_date();
        String returnDate=bsv1.getReturn_date();
        String cusName=bsv1.getCustomer_name();
        String cusPhone=bsv1.getCustomer_number();
        String tot=bsv1.getTotal();
        int bookingID=bsv1.getBookingId();
        String advAmt=bsv1.getAdvancePayment();
        String collateral=bsv1.getCollateral();
        
//        setting the fields:
setFields(vehicleNo,brand,model,specialReq,borrowDate,returnDate,cusName,cusPhone,tot,bookingID,advAmt,collateral);
    }
    
public void setFields(String Vno,String Brand,String Model,String SpecialReq,String BorrowDate,String ReturnDate,String CusName,String CusPhone,String Total, int bookingId, String advAmt,String Collateral){
    slip_vehicleNo.setText(Vno);
    slip_brand.setText(Brand);
    slip_model.setText(Model);
    slip_specialReq1.setText(SpecialReq);
    slip_borrowDate1.setText(BorrowDate);
    slip_returnDate1.setText(ReturnDate);
    slip_cusName1.setText(CusName);
    slip_cusPhone1.setText(CusPhone);
    slip_Total.setText(String.valueOf(Total));
    slip_bookingNo.setText(String.valueOf(bookingId));
    slip_advanceAmt.setText(advAmt);
    slip_collateral.setText(Collateral);
    double dues=Double.parseDouble(Total)-Double.parseDouble(advAmt);
    slip_DueRemaining.setText(String.valueOf(dues));
}
 public void printSlip() {
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setPrintable(new Printable() {
            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                if (pageIndex > 0) {
                    return NO_SUCH_PAGE;
                }

                Graphics2D g2d = (Graphics2D) graphics;
                g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());

                slipPannel.printAll(graphics);

                return PAGE_EXISTS;
            }
        });

        if (job.printDialog()) {
            try {
                job.print();
            } catch (PrinterException e) {
                e.printStackTrace();
            }
        }
    }
 
// To save as PDF
 public static void savePanelAsPDF(JPanel panel, String filePath) {
        Document document = new Document();
        try {
            PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(filePath));
            document.open();
            com.itextpdf.text.pdf.PdfContentByte contentByte = writer.getDirectContent();
            com.itextpdf.text.pdf.PdfTemplate template = contentByte.createTemplate(panel.getWidth(), panel.getHeight());
            Graphics2D g2d = template.createGraphics(panel.getWidth(), panel.getHeight());
            panel.print(g2d);
            g2d.dispose();
            contentByte.addTemplate(template, 0, 0);
        } catch (DocumentException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (document != null) {
                document.close();
            }
        }}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_printSlip = new javax.swing.JButton();
        btn_savePDF = new javax.swing.JButton();
        slipPannel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        slip_bookingNo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        slip_advanceAmt = new javax.swing.JLabel();
        slip_collateral = new javax.swing.JLabel();
        slip_DueRemaining = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        slip_vehicleNo = new javax.swing.JLabel();
        slip_brand = new javax.swing.JLabel();
        slip_model = new javax.swing.JLabel();
        slip_specialReq1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        slip_borrowDate1 = new javax.swing.JLabel();
        slip_returnDate1 = new javax.swing.JLabel();
        slip_cusName1 = new javax.swing.JLabel();
        slip_cusPhone1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        slip_Total = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(224, 248, 255));
        jPanel1.setLayout(null);

        btn_printSlip.setBackground(new java.awt.Color(0, 69, 64));
        btn_printSlip.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        btn_printSlip.setForeground(new java.awt.Color(255, 255, 255));
        btn_printSlip.setText("Print Slip");
        btn_printSlip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printSlipActionPerformed(evt);
            }
        });
        jPanel1.add(btn_printSlip);
        btn_printSlip.setBounds(290, 20, 140, 40);

        btn_savePDF.setBackground(new java.awt.Color(0, 0, 0));
        btn_savePDF.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        btn_savePDF.setForeground(new java.awt.Color(255, 255, 255));
        btn_savePDF.setText("Save PDF");
        btn_savePDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_savePDFActionPerformed(evt);
            }
        });
        jPanel1.add(btn_savePDF);
        btn_savePDF.setBounds(130, 20, 140, 40);

        slipPannel.setBackground(new java.awt.Color(255, 255, 255));
        slipPannel.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 51, 68));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BOOKING SLIP");
        slipPannel.add(jLabel1);
        jLabel1.setBounds(0, 6, 550, 56);

        jPanel2.setBackground(new java.awt.Color(23, 0, 57));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        slipPannel.add(jPanel2);
        jPanel2.setBounds(0, 0, 570, 60);

        slip_bookingNo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        slip_bookingNo.setForeground(new java.awt.Color(190, 26, 39));
        slip_bookingNo.setText("-");
        slipPannel.add(slip_bookingNo);
        slip_bookingNo.setBounds(300, 120, 230, 40);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 40, 107));
        jLabel3.setText("RideX Vehicle Rental Management System");
        slipPannel.add(jLabel3);
        jLabel3.setBounds(90, 70, 440, 30);

        slip_advanceAmt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        slip_advanceAmt.setText("-");
        slipPannel.add(slip_advanceAmt);
        slip_advanceAmt.setBounds(290, 550, 200, 40);

        slip_collateral.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        slip_collateral.setText("-");
        slipPannel.add(slip_collateral);
        slip_collateral.setBounds(300, 470, 230, 40);

        slip_DueRemaining.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        slip_DueRemaining.setText("-");
        slipPannel.add(slip_DueRemaining);
        slip_DueRemaining.setBounds(290, 580, 210, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Brand:");
        slipPannel.add(jLabel6);
        jLabel6.setBounds(30, 190, 160, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Model:");
        slipPannel.add(jLabel7);
        jLabel7.setBounds(30, 230, 160, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Special Request");
        slipPannel.add(jLabel8);
        jLabel8.setBounds(30, 270, 200, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Collateral deposited:");
        slipPannel.add(jLabel9);
        jLabel9.setBounds(30, 470, 230, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Return Date:");
        slipPannel.add(jLabel10);
        jLabel10.setBounds(30, 350, 160, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Borrow Date:");
        slipPannel.add(jLabel11);
        jLabel11.setBounds(30, 310, 160, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Customer Name:");
        slipPannel.add(jLabel12);
        jLabel12.setBounds(30, 390, 200, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(214, 64, 65));
        jLabel13.setText("Booking No:");
        slipPannel.add(jLabel13);
        jLabel13.setBounds(30, 120, 130, 40);

        slip_vehicleNo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        slip_vehicleNo.setText("-");
        slipPannel.add(slip_vehicleNo);
        slip_vehicleNo.setBounds(300, 160, 240, 40);

        slip_brand.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        slip_brand.setText("-");
        slipPannel.add(slip_brand);
        slip_brand.setBounds(300, 190, 240, 40);

        slip_model.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        slip_model.setText("-");
        slipPannel.add(slip_model);
        slip_model.setBounds(300, 220, 240, 40);

        slip_specialReq1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        slip_specialReq1.setText("-");
        slipPannel.add(slip_specialReq1);
        slip_specialReq1.setBounds(300, 260, 240, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/longbillborder.png"))); // NOI18N
        slipPannel.add(jLabel2);
        jLabel2.setBounds(10, 100, 540, 540);

        slip_borrowDate1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        slip_borrowDate1.setText("-");
        slipPannel.add(slip_borrowDate1);
        slip_borrowDate1.setBounds(300, 300, 230, 40);

        slip_returnDate1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        slip_returnDate1.setText("-");
        slipPannel.add(slip_returnDate1);
        slip_returnDate1.setBounds(300, 340, 230, 40);

        slip_cusName1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        slip_cusName1.setText("-");
        slipPannel.add(slip_cusName1);
        slip_cusName1.setBounds(300, 380, 240, 40);

        slip_cusPhone1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        slip_cusPhone1.setText("-");
        slipPannel.add(slip_cusPhone1);
        slip_cusPhone1.setBounds(300, 420, 240, 40);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Vehicle No.:");
        slipPannel.add(jLabel14);
        jLabel14.setBounds(30, 150, 160, 40);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("Customer Phone:");
        slipPannel.add(jLabel15);
        jLabel15.setBounds(30, 430, 200, 40);

        slip_Total.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        slip_Total.setText("-");
        slipPannel.add(slip_Total);
        slip_Total.setBounds(290, 520, 230, 40);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("Advance Payment");
        slipPannel.add(jLabel16);
        jLabel16.setBounds(60, 550, 200, 40);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setText("Total");
        slipPannel.add(jLabel17);
        jLabel17.setBounds(60, 520, 160, 40);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setText("Due Remaining");
        slipPannel.add(jLabel18);
        jLabel18.setBounds(60, 580, 210, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slipPannel, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(slipPannel, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(586, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_printSlipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printSlipActionPerformed
printSlip();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_printSlipActionPerformed

    private void btn_savePDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_savePDFActionPerformed
        String pathToSavePDF="C:\\Users\\hello\\OneDrive\\Documents\\BookingSlips\\slip.pdf";
        savePanelAsPDF(slipPannel,pathToSavePDF);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_savePDFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingSlipView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingSlipView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingSlipView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingSlipView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingSlipView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_printSlip;
    private javax.swing.JButton btn_savePDF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel slipPannel;
    private javax.swing.JLabel slip_DueRemaining;
    private javax.swing.JLabel slip_Total;
    private javax.swing.JLabel slip_advanceAmt;
    private javax.swing.JLabel slip_bookingNo;
    private javax.swing.JLabel slip_borrowDate1;
    private javax.swing.JLabel slip_brand;
    private javax.swing.JLabel slip_collateral;
    private javax.swing.JLabel slip_cusName1;
    private javax.swing.JLabel slip_cusPhone1;
    private javax.swing.JLabel slip_model;
    private javax.swing.JLabel slip_returnDate1;
    private javax.swing.JLabel slip_specialReq1;
    private javax.swing.JLabel slip_vehicleNo;
    // End of variables declaration//GEN-END:variables
}
