/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


/**
 *
 * @author hello
 */
public class BookingSlipView extends javax.swing.JFrame {

    /**
     * Creates new form BookingSlipView
     */
    public BookingSlipView() {
        initComponents();
    }
    
public void setFields(String Vno,String Brand,String Model,String SpecialReq,String BorrowDate,String ReturnDate,String CusName,String CusPhone,double Total){
    slip_vehicleNo1.setText(Vno);
    slip_brand.setText(Brand);
    slip_model.setText(Model);
    slip_specialReq1.setText(SpecialReq);
    slip_borrowDate1.setText(BorrowDate);
    slip_returnDate1.setText(ReturnDate);
    slip_cusName1.setText(CusName);
    slip_cusPhone1.setText(CusPhone);
    slip_Total.setText(String.valueOf(Total));
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        slip_Total = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        slip_vehicleNo1 = new javax.swing.JLabel();
        slip_brand = new javax.swing.JLabel();
        slip_model = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        slip_specialReq1 = new javax.swing.JLabel();
        slip_borrowDate1 = new javax.swing.JLabel();
        slip_returnDate1 = new javax.swing.JLabel();
        slip_cusName1 = new javax.swing.JLabel();
        slip_cusPhone1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 51, 68));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BOOKING SLIP");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 6, 555, 56);

        jPanel2.setBackground(new java.awt.Color(23, 0, 57));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 560, 60);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 40, 107));
        jLabel3.setText("RideX Vehicle Rental Management System");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 70, 440, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Total");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 450, 160, 40);

        slip_Total.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        slip_Total.setText("-");
        jPanel1.add(slip_Total);
        slip_Total.setBounds(300, 450, 160, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Brand:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 160, 160, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Model:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 200, 160, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Special Request");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 240, 200, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Customer Phone:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 400, 200, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Return Date:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 320, 160, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Borrow Date:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(30, 280, 160, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Customer Name:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(30, 360, 200, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("Vehicle No.:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(30, 120, 160, 40);

        slip_vehicleNo1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        slip_vehicleNo1.setText("-");
        jPanel1.add(slip_vehicleNo1);
        slip_vehicleNo1.setBounds(300, 120, 160, 40);

        slip_brand.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        slip_brand.setText("-");
        jPanel1.add(slip_brand);
        slip_brand.setBounds(300, 160, 160, 40);

        slip_model.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        slip_model.setText("-");
        jPanel1.add(slip_model);
        slip_model.setBounds(300, 190, 160, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/longbillborder.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 90, 540, 440);

        slip_specialReq1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        slip_specialReq1.setText("-");
        jPanel1.add(slip_specialReq1);
        slip_specialReq1.setBounds(300, 230, 160, 40);

        slip_borrowDate1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        slip_borrowDate1.setText("-");
        jPanel1.add(slip_borrowDate1);
        slip_borrowDate1.setBounds(300, 270, 160, 40);

        slip_returnDate1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        slip_returnDate1.setText("-");
        jPanel1.add(slip_returnDate1);
        slip_returnDate1.setBounds(300, 310, 160, 40);

        slip_cusName1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        slip_cusName1.setText("-");
        jPanel1.add(slip_cusName1);
        slip_cusName1.setBounds(300, 350, 160, 40);

        slip_cusPhone1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        slip_cusPhone1.setText("-");
        jPanel1.add(slip_cusPhone1);
        slip_cusPhone1.setBounds(300, 390, 160, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingSlipView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingSlipView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingSlipView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingSlipView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingSlipView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel slip_Total;
    private javax.swing.JLabel slip_borrowDate1;
    private javax.swing.JLabel slip_brand;
    private javax.swing.JLabel slip_cusName1;
    private javax.swing.JLabel slip_cusPhone1;
    private javax.swing.JLabel slip_model;
    private javax.swing.JLabel slip_returnDate1;
    private javax.swing.JLabel slip_specialReq1;
    private javax.swing.JLabel slip_vehicleNo1;
    // End of variables declaration//GEN-END:variables
}
