   
package View;
import DAO.dbConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import View.BookingSlipView;
import Model.BookingSlipModel; 
import com.toedter.calendar.JCalendar;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import Model.ReturnModel;
import java.text.ParseException;
import java.util.concurrent.TimeUnit;
/**
 * @author helloe
 */
public class ReturnVehicle extends javax.swing.JFrame {
private int bookingId;
private double total, rate,advancePayment;
Date returnDate;

    /**
     * Creates new form BookingsView
     */
    public ReturnVehicle() {
        initComponents();
    }

    
    public void searchBooking(){
                String bookingIdString = ret_bkNo.getText();
                  if (bookingIdString.isEmpty()) {
                      JOptionPane.showMessageDialog(this, "Please enter a booking ID.");
                      return;
                  }

                  try {
                      // Validate and parse the booking ID
                      bookingId = Integer.parseInt(bookingIdString);
                  } catch (NumberFormatException ex) {
                      JOptionPane.showMessageDialog(this, "Invalid booking ID. Please enter a valid integer.");
                      return;
                  }

                try {
                    // Connect to the database
                    Connection connection = dbConnection.dbconnect();

                    // Prepare the SQL query
                    String query = "SELECT * FROM booking WHERE bookingId = ?";
                    PreparedStatement statement = connection.prepareStatement(query);
                    statement.setInt(1, bookingId);

                    // Execute the query
                    ResultSet resultSet = statement.executeQuery();

                    // Process the results
                    if (resultSet.next()) {
                        String vehicleNo = resultSet.getString("vehicleNo");
                       
                        Date bookingDate = resultSet.getDate("bookingDate");
                        returnDate = resultSet.getDate("returnDate");
                        String specialRequest = resultSet.getString("specialRequest");
                        total = resultSet.getDouble("total");
                        advancePayment = resultSet.getDouble("advancePayment");
                        String collateral = resultSet.getString("collateral");
                        int customerId = resultSet.getInt("customerID");
                        rate= resultSet.getDouble("rate");

                        labVehicleNo.setText(vehicleNo);
                        labCusPhone.setText(getCustomerPhone(customerId));
                        cusName.setText(getCustomerName(customerId));
                        labCollateral.setText(collateral);
                        labBookDate.setText(String.valueOf(bookingDate));
                        labExpectRetDate.setText(String.valueOf(returnDate));
                        labBookAmt.setText(String.valueOf(total));
                        labAdvanceAmt.setText(String.valueOf(advancePayment));                      
                      
                    } else {
                       JOptionPane.showMessageDialog(this, "No booking found with the specified ID.");
                    }

                    // Close the connections and statement
                    resultSet.close();
                    statement.close();
                    connection.close();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
    }
    /**
     * This method is called from within the constructor to initialize the form.WARNING: Do NOT modify this code.The content of this method is always
 regenerated by the Form Editor.
     * @param expectedReturnDate
     * @param Rate
     */
 public void proceedBooking(String expectedReturnDate,double Rate,double bookingAmt,double AdvanceAmt){
       Date actualRetDate = ActualReturnDate.getDate();
       String damageCharge=txtDamageCharge.getText();
       double FineAmt=calculateFine(expectedReturnDate,actualRetDate,Rate);
       txtLateFee.setText(String.valueOf("Rs. "+FineAmt));
       labDamageCharge.setText("Rs. "+damageCharge);
       double GrandTotal=bookingAmt+FineAmt+ Double.parseDouble(damageCharge);
       labTotal.setText(String.valueOf(GrandTotal));
       double RemainingAmt=GrandTotal-AdvanceAmt;
       labRemainingAmt.setText(String.valueOf(RemainingAmt));

 }
   
public static double calculateFine(String expectedReturnDateString, Date actualReturnDate, double rate) {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Date expectedReturnDate = dateFormat.parse(expectedReturnDateString);
            long differenceInMilliseconds = actualReturnDate.getTime() - expectedReturnDate.getTime();
            long differenceInDays = TimeUnit.DAYS.convert(differenceInMilliseconds, TimeUnit.MILLISECONDS);

            if (differenceInDays <= 0) {
                return 0.0; // No fine if returned on or before the expected return date
            }

            double fine = rate * 1.5 * differenceInDays;
            return fine;
        } catch (ParseException ex) {
            ex.printStackTrace();
            return 0.0; // Return 0.0 in case of parsing error
        }
}
      
    public static String getCustomerPhone(int cusID) {
        String customerPhone = null;
        try {
            // Connect to the database
            Connection connection = dbConnection.dbconnect();

            // Prepare the SQL query
            String query = "SELECT phone_number FROM customer WHERE cusID = ?";
            PreparedStatement statement = connection.prepareStatement(query);
            statement.setInt(1, cusID);

            // Execute the query
            ResultSet resultSet = statement.executeQuery();

            // Process the result
            if (resultSet.next()) {
                customerPhone = resultSet.getString("phone_number");
            }

            // Close the connections and statement
            resultSet.close();
            statement.close();
            connection.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        return customerPhone;
    }
    
      public static String getCustomerName(int cusID) {
        String customerPhone = null;
        try {
            // Connect to the database
            Connection connection = dbConnection.dbconnect();

            // Prepare the SQL query
            String query = "SELECT full_name FROM customer WHERE cusID = ?";
            PreparedStatement statement = connection.prepareStatement(query);
            statement.setInt(1, cusID);

            // Execute the query
            ResultSet resultSet = statement.executeQuery();

            // Process the result
            if (resultSet.next()) {
                customerPhone = resultSet.getString("full_name");
            }

            // Close the connections and statement
            resultSet.close();
            statement.close();
            connection.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        return customerPhone;
    }
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        NavBar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        navbtn_Billing = new javax.swing.JButton();
        navbtn_Dashboard = new javax.swing.JButton();
        navbtn_Vehicles = new javax.swing.JButton();
        navbtn_Booking = new javax.swing.JButton();
        navbtn_Customers = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ActualReturnDate = new com.toedter.calendar.JDateChooser();
        labDamageCharge = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        labTotal = new javax.swing.JLabel();
        txtLateFee = new javax.swing.JLabel();
        txtDamageCharge = new javax.swing.JTextField();
        labAdvanceAmt = new javax.swing.JLabel();
        labRemainingAmt = new javax.swing.JLabel();
        labBookAmt = new javax.swing.JLabel();
        labVehicleNo = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        labCusPhone = new javax.swing.JLabel();
        labCollateral = new javax.swing.JLabel();
        labBookDate = new javax.swing.JLabel();
        labExpectRetDate = new javax.swing.JLabel();
        cusName = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ret_bkNo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_calculate1 = new javax.swing.JButton();
        btn_calculate = new javax.swing.JButton();
        bg_booking = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_Book = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel16.setFont(new java.awt.Font("Dubai", 0, 36)); // NOI18N
        jLabel16.setText("DASHBOARD");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NavBar.setBackground(new java.awt.Color(221, 229, 239));
        NavBar.setDoubleBuffered(false);
        NavBar.setLayout(null);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        NavBar.add(jLabel9);
        jLabel9.setBounds(10, 10, 140, 170);

        navbtn_Billing.setBackground(new java.awt.Color(11, 16, 65));
        navbtn_Billing.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        navbtn_Billing.setForeground(new java.awt.Color(255, 255, 255));
        navbtn_Billing.setText("Billing");
        navbtn_Billing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navbtn_BillingActionPerformed(evt);
            }
        });
        NavBar.add(navbtn_Billing);
        navbtn_Billing.setBounds(0, 530, 160, 40);

        navbtn_Dashboard.setBackground(new java.awt.Color(11, 16, 65));
        navbtn_Dashboard.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        navbtn_Dashboard.setForeground(new java.awt.Color(255, 255, 255));
        navbtn_Dashboard.setText("Dashboard");
        navbtn_Dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navbtn_DashboardActionPerformed(evt);
            }
        });
        NavBar.add(navbtn_Dashboard);
        navbtn_Dashboard.setBounds(0, 330, 160, 40);

        navbtn_Vehicles.setBackground(new java.awt.Color(11, 16, 65));
        navbtn_Vehicles.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        navbtn_Vehicles.setForeground(new java.awt.Color(255, 255, 255));
        navbtn_Vehicles.setText("Vehicles");
        navbtn_Vehicles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navbtn_VehiclesActionPerformed(evt);
            }
        });
        NavBar.add(navbtn_Vehicles);
        navbtn_Vehicles.setBounds(0, 430, 160, 40);

        navbtn_Booking.setBackground(new java.awt.Color(11, 16, 65));
        navbtn_Booking.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        navbtn_Booking.setForeground(new java.awt.Color(255, 255, 255));
        navbtn_Booking.setText("Booking");
        navbtn_Booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navbtn_BookingActionPerformed(evt);
            }
        });
        NavBar.add(navbtn_Booking);
        navbtn_Booking.setBounds(0, 480, 160, 40);

        navbtn_Customers.setBackground(new java.awt.Color(11, 16, 65));
        navbtn_Customers.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        navbtn_Customers.setForeground(new java.awt.Color(255, 255, 255));
        navbtn_Customers.setText("Customers");
        navbtn_Customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navbtn_CustomersActionPerformed(evt);
            }
        });
        NavBar.add(navbtn_Customers);
        navbtn_Customers.setBounds(0, 380, 160, 40);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);
        jPanel2.add(ActualReturnDate);
        ActualReturnDate.setBounds(300, 540, 190, 30);

        labDamageCharge.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labDamageCharge.setForeground(new java.awt.Color(153, 0, 0));
        labDamageCharge.setText("-");
        jPanel2.add(labDamageCharge);
        labDamageCharge.setBounds(990, 200, 200, 29);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 39, 76));
        jLabel20.setText("Damage Charge:");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(790, 200, 190, 29);

        labTotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labTotal.setForeground(new java.awt.Color(153, 0, 0));
        labTotal.setText("-");
        jPanel2.add(labTotal);
        labTotal.setBounds(990, 240, 200, 29);

        txtLateFee.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtLateFee.setForeground(new java.awt.Color(153, 0, 0));
        txtLateFee.setText("-");
        jPanel2.add(txtLateFee);
        txtLateFee.setBounds(990, 160, 270, 29);

        txtDamageCharge.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDamageCharge.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDamageCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDamageChargeActionPerformed(evt);
            }
        });
        jPanel2.add(txtDamageCharge);
        txtDamageCharge.setBounds(300, 580, 190, 40);

        labAdvanceAmt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labAdvanceAmt.setForeground(new java.awt.Color(153, 0, 0));
        labAdvanceAmt.setText("-");
        jPanel2.add(labAdvanceAmt);
        labAdvanceAmt.setBounds(990, 290, 200, 29);

        labRemainingAmt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labRemainingAmt.setForeground(new java.awt.Color(153, 0, 0));
        labRemainingAmt.setText("-");
        jPanel2.add(labRemainingAmt);
        labRemainingAmt.setBounds(1040, 330, 200, 29);

        labBookAmt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labBookAmt.setForeground(new java.awt.Color(153, 0, 0));
        labBookAmt.setText("-");
        jPanel2.add(labBookAmt);
        labBookAmt.setBounds(990, 120, 270, 29);

        labVehicleNo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labVehicleNo.setForeground(new java.awt.Color(153, 0, 0));
        labVehicleNo.setText("-");
        jPanel2.add(labVehicleNo);
        labVehicleNo.setBounds(230, 300, 270, 29);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 39, 76));
        jLabel24.setText("Remaining Amount:");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(790, 330, 250, 29);

        labCusPhone.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labCusPhone.setForeground(new java.awt.Color(153, 0, 0));
        labCusPhone.setText("-");
        jPanel2.add(labCusPhone);
        labCusPhone.setBounds(360, 380, 210, 29);

        labCollateral.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labCollateral.setForeground(new java.awt.Color(153, 0, 0));
        labCollateral.setText("-");
        jPanel2.add(labCollateral);
        labCollateral.setBounds(300, 420, 200, 30);

        labBookDate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labBookDate.setForeground(new java.awt.Color(153, 0, 0));
        labBookDate.setText("-");
        jPanel2.add(labBookDate);
        labBookDate.setBounds(230, 460, 190, 29);

        labExpectRetDate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labExpectRetDate.setForeground(new java.awt.Color(153, 0, 0));
        labExpectRetDate.setText("-");
        jPanel2.add(labExpectRetDate);
        labExpectRetDate.setBounds(320, 500, 220, 29);

        cusName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cusName.setForeground(new java.awt.Color(153, 0, 0));
        cusName.setText("-");
        jPanel2.add(cusName);
        cusName.setBounds(260, 340, 200, 29);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 39, 76));
        jLabel19.setText("Damage Charge:");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(70, 580, 190, 29);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 39, 76));
        jLabel21.setText("Total:");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(790, 240, 100, 29);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 39, 76));
        jLabel22.setText("Advance Paid:");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(790, 290, 170, 29);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 39, 76));
        jLabel23.setText("Late Fee:");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(790, 160, 240, 29);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 39, 76));
        jLabel10.setText("Customer Phone Number:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(70, 380, 280, 29);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 39, 76));
        jLabel18.setText("Booking Amount:");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(790, 120, 240, 29);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 39, 76));
        jLabel11.setText("Expected Return Date:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(70, 500, 280, 29);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 39, 76));
        jLabel12.setText("Actual Return Date:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(70, 540, 240, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 39, 76));
        jLabel2.setText("Customer Name:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(70, 340, 180, 29);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 39, 76));
        jLabel13.setText("Booking Date:");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(70, 460, 190, 29);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 39, 76));
        jLabel1.setText("Vehicle No:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(70, 300, 140, 29);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 39, 76));
        jLabel14.setText("Booking No");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(100, 100, 180, 40);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 39, 76));
        jLabel17.setText("Collateral Deposited:");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(70, 420, 240, 29);

        ret_bkNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ret_bkNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ret_bkNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ret_bkNoActionPerformed(evt);
            }
        });
        jPanel2.add(ret_bkNo);
        ret_bkNo.setBounds(270, 100, 250, 40);

        jLabel5.setFont(new java.awt.Font("Yu Gothic Medium", 1, 48)); // NOI18N
        jLabel5.setText("CHECKOUT");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(60, 10, 580, 80);

        btn_calculate1.setBackground(new java.awt.Color(154, 57, 23));
        btn_calculate1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_calculate1.setForeground(new java.awt.Color(255, 255, 255));
        btn_calculate1.setText("Proceed");
        btn_calculate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calculate1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_calculate1);
        btn_calculate1.setBounds(230, 670, 230, 40);

        btn_calculate.setBackground(new java.awt.Color(154, 57, 23));
        btn_calculate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_calculate.setForeground(new java.awt.Color(255, 255, 255));
        btn_calculate.setText("Search Booking");
        btn_calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calculateActionPerformed(evt);
            }
        });
        jPanel2.add(btn_calculate);
        btn_calculate.setBounds(230, 170, 230, 40);

        bg_booking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/searchbookingBG.png"))); // NOI18N
        jPanel2.add(bg_booking);
        bg_booking.setBounds(30, 70, 620, 180);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/returnpageBG2.png"))); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(30, 270, 650, 390);

        btn_Book.setBackground(new java.awt.Color(154, 57, 23));
        btn_Book.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_Book.setForeground(new java.awt.Color(255, 255, 255));
        btn_Book.setText("Confirm Checkout");
        btn_Book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BookActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Book);
        btn_Book.setBounds(970, 370, 220, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/returnpageBG2.png"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(700, 60, 630, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(NavBar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NavBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void navbtn_BillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navbtn_BillingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_navbtn_BillingActionPerformed

    private void navbtn_DashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navbtn_DashboardActionPerformed
        // TODO add your handling code here:
        new DashboardView().setVisible(true);
        dispose();
    }//GEN-LAST:event_navbtn_DashboardActionPerformed

    private void navbtn_VehiclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navbtn_VehiclesActionPerformed
        // TODO add your handling code here:
        new VehiclesView().setVisible(true);
        dispose();
    }//GEN-LAST:event_navbtn_VehiclesActionPerformed

    private void navbtn_BookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navbtn_BookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_navbtn_BookingActionPerformed
 
    
    private void ret_bkNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ret_bkNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ret_bkNoActionPerformed

    private void btn_BookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BookActionPerformed
//String[] bookData=new String[8];

    }//GEN-LAST:event_btn_BookActionPerformed

    private void btn_calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calculateActionPerformed
searchBooking();
    }//GEN-LAST:event_btn_calculateActionPerformed

    private void navbtn_CustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navbtn_CustomersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_navbtn_CustomersActionPerformed

    private void btn_calculate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calculate1ActionPerformed
proceedBooking(String.valueOf(returnDate),rate,total,advancePayment);
    }//GEN-LAST:event_btn_calculate1ActionPerformed

    private void txtDamageChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDamageChargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDamageChargeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnVehicle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser ActualReturnDate;
    private javax.swing.JPanel NavBar;
    private javax.swing.JLabel bg_booking;
    private javax.swing.JButton btn_Book;
    private javax.swing.JButton btn_calculate;
    private javax.swing.JButton btn_calculate1;
    private javax.swing.JLabel cusName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labAdvanceAmt;
    private javax.swing.JLabel labBookAmt;
    private javax.swing.JLabel labBookDate;
    private javax.swing.JLabel labCollateral;
    private javax.swing.JLabel labCusPhone;
    private javax.swing.JLabel labDamageCharge;
    private javax.swing.JLabel labExpectRetDate;
    private javax.swing.JLabel labRemainingAmt;
    private javax.swing.JLabel labTotal;
    private javax.swing.JLabel labVehicleNo;
    private javax.swing.JButton navbtn_Billing;
    private javax.swing.JButton navbtn_Booking;
    private javax.swing.JButton navbtn_Customers;
    private javax.swing.JButton navbtn_Dashboard;
    private javax.swing.JButton navbtn_Vehicles;
    private javax.swing.JTextField ret_bkNo;
    private javax.swing.JTextField txtDamageCharge;
    private javax.swing.JLabel txtLateFee;
    // End of variables declaration//GEN-END:variables
}
